apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serhatsari-cert
  namespace: istio-system
spec:
  secretName: serhatsari-dev-tls
  issuerRef:
    name: letsencrypt-subdomain
    kind: ClusterIssuer
  commonName: "*.serhatsari.dev"
  dnsNames:
    - "*.serhatsari.dev"
